"""
Chronicle Log Viewer - Interactive visualization tool for LeeQ experiment data.

This module provides a web-based dashboard for loading and visualizing chronicle
log files from LeeQ experiments. It leverages Dash and Plotly to create an
interactive interface that can display various plots generated by experiment
browser functions.

Features:
    - Load chronicle log files (.hdf5) from file paths
    - Automatically discover available plot functions
    - Display experiment metadata and information
    - Generate and display interactive Plotly figures
    - Handle various error conditions gracefully
    - Provide visual feedback with loading states

Requirements:
    - dash >= 2.0.0
    - dash-bootstrap-components >= 1.0.0
    - plotly >= 5.0.0
    - leeq (with chronicle support)

Usage:
    Run as a standalone application:
        python chronicle_viewer.py

    Or import and customize:
        from chronicle_viewer import app
        app.run(debug=True)

Author: LeeQ Development Team
Version: 2.0.0
"""

import dash
from dash import dcc, html, Input, Output, State, callback_context, ALL
from dash.exceptions import PreventUpdate
import dash.dependencies
import dash_bootstrap_components as dbc
from leeq.chronicle import load_object
import plotly.graph_objects as go
import json
import argparse

# Import shared components from common module
from leeq.chronicle.viewer.common import (
    get_html_template,
    convert_figure_to_plotly,
    create_tree_view_items,
    render_tree_nodes,
    create_experiment_attributes_panel,
    create_header_layout,
    create_plot_display_section
)

# Initialize Dash app with Bootstrap theme
app = dash.Dash(__name__, external_stylesheets=[
    dbc.themes.BOOTSTRAP,
    "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
])

# Use common HTML template with CSS and JavaScript
app.index_string = get_html_template(title="Chronicle Log Viewer")

# Main app layout with full-height sidebar design
app.layout = dbc.Container([
    # Header
    create_header_layout(
        "Chronicle Log Viewer",
        "Load and visualize LeeQ experiment chronicle files"
    ),

    # Main layout with resizable three panels
    html.Div([
        # Left Sidebar - File & Experiment Selection (Resizable)
        html.Div([
            dbc.Card([
                dbc.CardHeader([
                    html.I(className="bi bi-folder-open me-2"),
                    html.Strong("File & Experiment Selection"),
                    html.Small(" (drag right edge to resize)", className="text-muted ms-2")
                ]),
                dbc.CardBody([
                    # File input section
                    html.Div([
                        dbc.Label("Chronicle Log File:", className="fw-bold mb-2"),
                        dbc.InputGroup([
                            dbc.Input(
                                id="file-path",
                                placeholder="Enter file path...",
                                type="text",
                                className="form-control",
                                size="sm"
                            ),
                            dbc.InputGroupText(
                                dbc.Spinner(
                                    html.Span(id="loading-indicator", children=""),
                                    size="sm",
                                    spinner_style={"display": "none"},
                                    id="file-spinner"
                                )
                            ),
                        ], className="mb-3"),
                    ], className="file-input-section"),

                    # Experiment selection section
                    html.Div([
                        html.Hr(className="my-3"),
                        html.Div(id="experiment-selector-container", children=[], className=""),
                    ], className="experiment-section")
                ])
            ], className="sidebar-card"),
            # Resize handle
            html.Div(className="resize-handle", title="Drag to resize sidebar")
        ], className="sidebar-resizable"),

        # Right Content Area - Plot & Attributes
        html.Div([
            dbc.Row([
                # Main Content Area - Plot & Controls
                dbc.Col([
                    dbc.Card([
                        dbc.CardBody([
                            # Experiment info section
                            dcc.Loading(
                                id="loading-exp-info",
                                type="circle",
                                children=html.Div(id="experiment-info", className="mb-3"),
                                color="#0d6efd"
                            ),

                            # Plot controls section
                            dcc.Loading(
                                id="loading-plot-controls",
                                type="dot",
                                children=html.Div(id="plot-controls", className="mb-3"),
                                color="#0d6efd"
                            ),

                            # Plot display section
                            create_plot_display_section(),
                        ])
                    ], className="main-content-card")
                ], width=8, className="main-content-column pe-2"),

                # Right Panel - Experiment Attributes
                dbc.Col([
                    dbc.Card([
                        dbc.CardHeader([
                            html.I(className="bi bi-info-circle me-2"),
                            html.Strong("Experiment Attributes")
                        ]),
                        dbc.CardBody([
                            dcc.Loading(
                                id="loading-attributes",
                                type="dot",
                                children=html.Div(
                                    id="experiment-attributes",
                                    children=[
                                        dbc.Alert(
                                            [
                                                html.I(className="bi bi-arrow-left me-2"),
                                                "Select an experiment to view its attributes"
                                            ],
                                            color="info",
                                            className="text-center"
                                        )
                                    ],
                                    className=""
                                ),
                                color="#0d6efd"
                            )
                        ])
                    ], className="attributes-card")
                ], width=4, className="attributes-column"),
            ], className="h-100")
        ], className="main-content-resizable")
    ], className="resizable-container content-row"),

    # Hidden storage for file path
    dcc.Store(id="file-store"),
], fluid=True, className="p-4 main-container", style={"maxWidth": "1600px"})


# ============================================================================
# File-Specific Functions
# ============================================================================

def build_experiment_tree(file_path):
    """
    Build a hierarchical tree structure of experiments from the chronicle file.
    Returns experiments organized by their entry paths with timestamps.

    This function is specific to file-based loading.
    """
    try:
        from leeq.chronicle import Chronicle
        chronicle = Chronicle()
        record_book = chronicle.open_record_book(file_path.strip())
        record_ids = record_book.get_available_record_ids()

        if not record_ids:
            return []

        # Collect all experiments with their paths and timestamps
        experiments = []
        for record_id in record_ids:
            try:
                record = record_book.get_record_by_id(record_id)
                entry_path = str(record.get_path())
                timestamp = record.timestamp

                experiments.append({
                    'record_id': record_id,
                    'entry_path': entry_path,
                    'timestamp': timestamp,
                    'path_parts': entry_path.strip('/').split('/')[1:]  # Remove '/root' prefix
                })
            except Exception:
                continue

        # Sort by timestamp (older first)
        experiments.sort(key=lambda x: x['timestamp'])

        return experiments

    except Exception as e:
        raise e


# ============================================================================
# File-Specific Callbacks
# ============================================================================

# Callback for populating experiment selector when file is loaded
@app.callback(
    Output("experiment-selector-container", "children"),
    Input("file-path", "value"),
    prevent_initial_call=True
)
def populate_experiment_selector(file_path):
    """
    Populate experiment selector with a tree view when a file is loaded.
    Returns a tree structure with all available experiments organized hierarchically.
    """
    if not file_path:
        return []

    try:
        experiments = build_experiment_tree(file_path)

        if not experiments:
            return [
                dbc.Alert(
                    "No experiments found in this chronicle file.",
                    color="warning",
                    className="mb-3"
                )
            ]

        # Create tree structure using common functions
        tree_nodes = create_tree_view_items(experiments)
        tree_items = render_tree_nodes(tree_nodes)

        return [
            dbc.Label("Select Experiment:", className="fw-bold mb-2"),
            html.Small(f"({len(experiments)} experiments, ordered by timestamp)",
                      className="text-muted mb-2 d-block"),
            html.Div(
                tree_items,
                className="experiment-tree border rounded p-2",
                style={
                    "backgroundColor": "#f8f9fa",
                    "fontSize": "0.9rem"
                }
            )
        ]

    except Exception as e:
        return [
            dbc.Alert(
                f"Error loading experiments: {str(e)[:200]}",
                color="danger",
                className="mb-3"
            )
        ]


# Callback for loading selected experiment and displaying info
@app.callback(
    [Output("experiment-info", "children"),
     Output("plot-controls", "children"),
     Output("experiment-attributes", "children"),
     Output("file-store", "data")],
    [Input({"type": "experiment-btn", "index": ALL}, "n_clicks")],
    [State("file-path", "value")],
    prevent_initial_call=True
)
def load_selected_experiment(n_clicks_list, file_path):
    """
    Load the selected chronicle experiment from the file and extract metadata.

    This callback is triggered when the user clicks an experiment button in the tree view.
    It loads the specific experiment using the record ID and prepares UI components.
    """
    # Determine which button was clicked
    ctx = callback_context
    if not ctx.triggered:
        raise PreventUpdate

    # Extract record_id from the triggered button
    triggered_id = ctx.triggered[0]['prop_id']
    if not triggered_id or 'experiment-btn' not in triggered_id:
        raise PreventUpdate

    # Parse the button ID to get the record_id
    button_id = json.loads(triggered_id.split('.')[0])
    selected_record_id = button_id['index']

    if not selected_record_id or not file_path or file_path.strip() == "":
        return (
            dbc.Alert(
                [
                    html.I(className="bi bi-info-circle-fill me-2"),
                    "Select an experiment from the dropdown to view details"
                ],
                color="info",
                className="d-flex align-items-center"
            ),
            [],
            create_experiment_attributes_panel(),
            None
        )

    try:
        # Load the specific experiment using the selected record ID
        experiment = load_object(file_path.strip(), record_id=selected_record_id)

        # Create experiment info display with improved styling
        exp_type = type(experiment).__name__

        # Try to get additional experiment attributes if available
        exp_attrs = []
        exp_attrs.append(html.P(f"Record ID: {selected_record_id}", className="mb-1 small"))
        exp_attrs.append(html.P(f"File: {file_path}", className="mb-1 small text-truncate"))

        if hasattr(experiment, '__dict__'):
            for attr in ['name', 'description', 'timestamp', 'date']:
                if hasattr(experiment, attr):
                    value = getattr(experiment, attr)
                    if value:
                        exp_attrs.append(html.P(f"{attr.title()}: {str(value)[:100]}", className="mb-1 small"))

        info_card = dbc.Card([
            dbc.CardBody([
                html.H5([
                    html.I(className="bi bi-check-circle-fill text-success me-2"),
                    "Experiment Loaded Successfully"
                ], className="card-title text-success"),
                html.Hr(className="my-2"),
                html.P([
                    html.Strong("Type: "),
                    html.Span(exp_type, className="font-monospace")
                ], className="mb-1"),
                html.P([
                    html.Strong("File: "),
                    html.Span(file_path.strip(), className="text-muted small font-monospace")
                ], className="mb-1"),
                *exp_attrs  # Include any additional attributes found
            ])
        ], color="success", outline=True, className="shadow-sm")

        # Get available plot functions using built-in method
        try:
            plot_functions = experiment.get_browser_functions()
        except AttributeError:
            # Experiment doesn't have get_browser_functions method
            store_data = {"file_path": file_path.strip(), "record_id": selected_record_id}
            attributes_panel = create_experiment_attributes_panel(experiment, selected_record_id)
            return (
                info_card,
                dbc.Alert(
                    [
                        html.I(className="bi bi-exclamation-triangle-fill me-2"),
                        "This experiment does not have browser functions available. ",
                        html.Small("(Missing get_browser_functions method)", className="text-muted")
                    ],
                    color="warning",
                    className="d-flex align-items-center"
                ),
                attributes_panel,
                store_data
            )

        if plot_functions:
            # Create buttons for each plot function
            buttons = []
            for name, method in plot_functions:
                btn = dbc.Button(
                    name.replace("_", " ").title(),
                    id={"type": "plot-btn", "index": name},
                    color="primary",
                    className="me-2 mb-2",
                    size="sm"
                )
                buttons.append(btn)

            plot_control_div = dbc.Card([
                dbc.CardBody([
                    html.H5([
                        html.I(className="bi bi-graph-up me-2"),
                        f"Available Plots ({len(plot_functions)})"
                    ], className="card-title mb-3 text-primary"),
                    html.P("Click a button below to generate and display the plot:", className="text-muted small mb-3"),
                    html.Div(buttons, className="d-flex flex-wrap")
                ])
            ], color="primary", outline=True, className="shadow-sm")

            # Store both file path and record ID for plot callbacks
            store_data = {"file_path": file_path.strip(), "record_id": selected_record_id}
            attributes_panel = create_experiment_attributes_panel(experiment, selected_record_id)
            return (info_card, plot_control_div, attributes_panel, store_data)
        else:
            store_data = {"file_path": file_path.strip(), "record_id": selected_record_id}
            attributes_panel = create_experiment_attributes_panel(experiment, selected_record_id)
            return (
                info_card,
                dbc.Alert("No plots available for this experiment", color="info"),
                attributes_panel,
                store_data
            )

    except FileNotFoundError:
        return (
            dbc.Alert(
                [
                    html.I(className="bi bi-x-circle-fill me-2"),
                    html.Strong("File Not Found"),
                    html.Br(),
                    html.Small(f"Path: {file_path}", className="font-monospace")
                ],
                color="danger",
                className="d-flex align-items-start"
            ),
            [],
            create_experiment_attributes_panel(error_msg="File not found"),
            {"file_path": file_path, "record_id": selected_record_id} if selected_record_id else None
        )
    except PermissionError:
        return (
            dbc.Alert(
                [
                    html.I(className="bi bi-shield-x me-2"),
                    html.Strong("Permission Denied"),
                    html.Br(),
                    html.Small(f"Cannot access: {file_path}", className="font-monospace")
                ],
                color="danger",
                className="d-flex align-items-start"
            ),
            [],
            create_experiment_attributes_panel(error_msg="Permission denied"),
            {"file_path": file_path, "record_id": selected_record_id} if selected_record_id else None
        )
    except Exception as e:
        # Generic error handling for other issues (corrupted files, etc.)
        error_msg = str(e)
        if "HDF5" in error_msg or "h5py" in error_msg:
            return (
                dbc.Alert(
                    [
                        html.I(className="bi bi-file-earmark-x me-2"),
                        html.Strong("Invalid Chronicle File"),
                        html.Br(),
                        html.Small("The file appears to be corrupted or is not a valid HDF5 chronicle file."),
                        html.Br(),
                        html.Details([
                            html.Summary("Technical Details", className="text-muted small mt-2"),
                            html.Pre(error_msg[:200], className="mt-2 p-2 bg-light small")
                        ])
                    ],
                    color="danger"
                ),
                [],
                create_experiment_attributes_panel(error_msg="Invalid chronicle file"),
                {"file_path": file_path, "record_id": selected_record_id} if selected_record_id else None
            )
        else:
            return (
                dbc.Alert(
                    [
                        html.I(className="bi bi-exclamation-octagon-fill me-2"),
                        html.Strong("Error Loading Experiment"),
                        html.Br(),
                        html.Small("An unexpected error occurred while loading the file."),
                        html.Br(),
                        html.Details([
                            html.Summary("Error Details", className="text-muted small mt-2"),
                            html.Pre(error_msg[:200], className="mt-2 p-2 bg-light small")
                        ])
                    ],
                    color="danger"
                ),
                [],
                create_experiment_attributes_panel(error_msg="Loading error"),
                {"file_path": file_path, "record_id": selected_record_id} if selected_record_id else None
            )


# Callback for displaying plots
@app.callback(
    Output("plot-display", "figure"),
    Input({"type": "plot-btn", "index": dash.dependencies.ALL}, "n_clicks"),
    State("file-store", "data"),
    prevent_initial_call=True
)
def display_plot(n_clicks, store_data):
    """
    Generate and display a plot based on the selected browser function.

    This callback is triggered when any plot button is clicked. It identifies
    which button was clicked, reloads the experiment, calls the corresponding
    browser function, and returns the generated Plotly figure.
    """
    if not store_data:
        return go.Figure().add_annotation(
            text="No experiment loaded",
            xref="paper", yref="paper",
            x=0.5, y=0.5, showarrow=False
        )

    file_path = store_data.get("file_path")
    record_id = store_data.get("record_id")

    if not file_path or not record_id:
        return go.Figure().add_annotation(
            text="Invalid experiment data",
            xref="paper", yref="paper",
            x=0.5, y=0.5, showarrow=False
        )

    # Get which button was clicked
    ctx = callback_context
    if not ctx.triggered:
        return go.Figure()

    # Extract the button ID that was clicked
    button_id = ctx.triggered[0]['prop_id']
    if '"index":' not in button_id:
        return go.Figure()

    # Parse the method name from the button ID
    button_dict = json.loads(button_id.split('.')[0])
    method_name = button_dict['index']

    try:
        # Load the specific experiment using the selected record ID
        experiment = load_object(file_path, record_id=record_id)

        plot_functions = experiment.get_browser_functions()

        # Find and call the selected plot method
        for name, method in plot_functions:
            if name == method_name:
                try:
                    fig = method()
                    # Convert figure to Plotly format (supports both Plotly and matplotlib)
                    plotly_fig = convert_figure_to_plotly(fig)
                    return plotly_fig
                except Exception as plot_error:
                    return go.Figure().add_annotation(
                        text=f"Error generating plot: {str(plot_error)[:200]}",
                        xref="paper", yref="paper",
                        x=0.5, y=0.5, showarrow=False
                    )

        return go.Figure().add_annotation(
            text=f"Plot method '{method_name}' not found",
            xref="paper", yref="paper",
            x=0.5, y=0.5, showarrow=False
        )

    except Exception as e:
        return go.Figure().add_annotation(
            text=f"Error loading experiment: {str(e)[:200]}",
            xref="paper", yref="paper",
            x=0.5, y=0.5, showarrow=False
        )


def main():
    """
    Main entry point for the chronicle viewer app.

    Starts the Dash server with configurable options.
    By default runs on http://localhost:8050 in debug mode.
    """
    parser = argparse.ArgumentParser(
        description="Chronicle Log Viewer - Visualize LeeQ experiment chronicle files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Usage Examples:
  Start the viewer on default port (8050):
    python chronicle_viewer.py

  Start on a different port:
    python chronicle_viewer.py --port 8080

  Start in production mode (no debug):
    python chronicle_viewer.py --no-debug

  View this help:
    python chronicle_viewer.py --help

Once started, open your browser to http://localhost:8050 (or the specified port)
and enter the path to a chronicle log file to visualize.
        """
    )
    parser.add_argument("--host", default="0.0.0.0", help="Host to run the server on")
    parser.add_argument("--port", type=int, default=8050, help="Port to run the server on")
    parser.add_argument("--no-debug", action="store_true", help="Disable debug mode")

    args = parser.parse_args()

    debug = not args.no_debug

    if debug:
        pass

    app.run(debug=debug, host=args.host, port=args.port)


if __name__ == "__main__":
    main()
