site_name: LeeQ Documentation
site_description: Quantum computing experiment orchestration framework
site_url: https://leeq.readthedocs.io

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: quick_start.md
    - Tutorial: tutorial.md
  - User Guide:
    - Core Concepts: guide/concepts.md
    - Experiments: guide/experiments.md
    - Calibrations: guide/calibrations.md
  - API Reference:
    - Core:
      - Base: api/core/base.md
      - Elements: api/core/elements.md
      - Engine: api/core/engine.md
      - Primitives: api/core/primitives.md
    - Experiments:
      - Builtin: api/experiments/builtin.md
      - Custom: api/experiments/base.md
    - Theory:
      - Simulation: api/theory/simulation.md
      - Tomography: api/theory/tomography.md
      - Optimal Control: api/theory/fits.md
      - Clifford Gates: api/theory/clifford.md
    - Compiler:
      - LBNL QubiC: api/compiler/lbnl_qubic.md
      - Base Classes: api/compiler/base.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Architecture: development/architecture.md
  - EPII:
    - Deployment Guide: epii/deployment-guide.md
    - Client Usage: epii/client-usage.md
    - Operations Guide: epii-operations-guide.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true