[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "leeq"
version = "0.0.1"
description = "LeeQ is a Python library for operating quantum circuits experiments."
authors = ["Shuxiang Cao <shuxiang.cao@scao.me>"]
license = "MIT"
packages = [
    { include = "leeq" },
]

[tool.poetry.dependencies]
python = "3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2"