name: pytest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout LabChronicle
        uses: actions/checkout@v4
        with:
          repository: ShuxiangCao/LabChronicle

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Lint with flake8
        run: |
          pip install flake8
          bash ./ci_scripts/lint.sh

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=. 
